# Generated by Django 2.1 on 2018-08-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobasic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
    ]
