# Generated by Django 2.1 on 2018-09-23 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangobasic', '0003_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('pub_date',)},
        ),
        migrations.AddField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
