# Generated by Django 2.1 on 2018-09-25 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangobasic', '0005_auto_20180925_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='djangobasic.Survey'),
            preserve_default=False,
        ),
    ]
